---
name: "Full Release"

on:
  push:
    # Only run when the pushed commit is tagged with #.#.#.
    tags:
      - "*.*.*"

jobs:
  tagged-release:
    name: "Full Release"
    runs-on: "ubuntu-latest"
    steps:
      # clone our repository into the runner
      - uses: actions/checkout@v2
      # install java on the runner
      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      # check that gradle is set up with a wrapper correctly
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      # make sure that our plugin builds
      - name: Build Project
        run: ./gradlew build
      # run any tests
      - name: Test Project
        run: ./gradlew test
      # see how much of the code is tested
      - name: Code Coverage
        uses: codecov/codecov-action@v2
      # build the jars
      - name: Build Jars
        run: ./gradlew jar
      # create a full release
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build"
          files: |
            build/libs/*.jar
